version: '2'
services:
  testmono04-app:
    image: testmono04
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testmono04-postgresql:5432/testmono04
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  testmono04-postgresql:
    extends:
      file: postgresql.yml
      service: testmono04-postgresql
